/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface TodoList {
        /**
          * String label
         */
        "label": string;
        /**
          * Option Type (used in value)
         */
        "optionType": string;
        /**
          * Array of name/value options
         */
        "options": string[];
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface TodoList {
        /**
          * String label
         */
        "label"?: string;
        /**
          * Emit a custom select event on value change
         */
        "onSelection"?: (event: CustomEvent<any>) => void;
        /**
          * Option Type (used in value)
         */
        "optionType"?: string;
        /**
          * Array of name/value options
         */
        "options"?: string[];
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
